[tool.poetry]
name = "akvile-turing-calculator"
version = "0.1.2"
description = "Calculator module for Turing College Data Science course Module 1 Sprint 1. Performs basic calculations with internal memory."
authors = ["GallantYami <landaiteakvile@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
isort = "^5.12.0"
black = "^23.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
