[project]
name = "bitint"
version = "0.1.2"
description = "Pure Python implementation of extended integer with named bits."
authors = [
    {name = "Robin Gottfried", email = "bitint@kebet.cz"},
]
keywords = ["bit", "int", "set", "flags", "namedtuple"]
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}

[project.urls]
repository = "https://github.com/czervenka/bit-int.git"
homepage = "https://github.com/czervenka/bit-int"
