[project]
name = "akami"
version = "0.0.2"
authors = [
  { name="akami", email="akami2733@gmail.com" },
]
description = "A small example package"
readme = "readmi.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
