[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simpleaudiocontroller"
version = "0.0.1"
authors = [
  { name="Anderson AraÃºjo", email="andersondev.ssh@gmail.com" },
]
description = "Simple interface for controlling audio devices"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Unix",
]

[project.urls]
"Homepage" = "https://github.com/andersonssh/simpleaudiocontroller"
"Bug Tracker" = "https://github.com/andersonssh/simpleaudiocontroller/issues"