[project]
name = "byquant"
version = "1.8.50"
dependencies = [
  "requests",
  "pandas",
  "quantstats",
  "IPython",
  "tushare",
  "akshare",
  "baostock",
  "ccxt>=4.0.43",
  "alpaca-py",
  "backtrader",
  "mplfinance"
  
]
