[package]
name = "ruff_python_stdlib"
version = "0.0.0"
publish = false
authors = ["Charlie Marsh <charlie.r.marsh@gmail.com>"]
edition = "2021"
rust-version = "1.71"
homepage = "https://beta.ruff.rs/docs"
documentation = "https://beta.ruff.rs/docs"
repository = "https://github.com/astral-sh/ruff"
license = "MIT"
resolver = "2"

[lib]

[dependencies]
unicode-ident = "1.0.11"
