[tool.poetry]
name = "pybrom"
version = "1.1.0"
description = "Brom client"
authors = ["Anton Rastyazhenko <rastyazhenko.anton@gmail.com>"]
readme = "README.md"
homepage = "https://brom.itworks.group"
documentation = "https://brom.itworks.group/documentation/python/"
repository = "https://git.albus.keenetic.pro/Python/brom"
packages = [
    { include = "brom.py", from = "src" }
]
include = []
exclude = []

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.3.0"
zeep = "^4.2.1"
requests = "^2.31.0"

[tool.poetry.group.build.dependencies]
setuptools = ">=68.0.0"
wheel = ">=0.40.0"

[tool.poetry.group.dev.dependencies]
pylint = ">=2.17.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
