[project]
name = "tello-dron-simple-flight"
version = "0.1.0"
description = "Take-off and landing and forward and reverse or right turn - end"
authors = [
    { name = "pysatellite", email = "pysatellite@gmail.com" },
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"

[project.license]
text = "GNU"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool]
