[build-system]
requires = ["setuptools"]


[project]
name = "paraty_commit_jlvillada"
version = "0.0.1"
authors = [
  { name="Jose Luis", email="jlvillada@paratytech.com" },
]
description = "Package to add precommit funcionality"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


