[package]
name = "ruff_workspace"
version = "0.0.0"
publish = false
authors = ["Charlie Marsh <charlie.r.marsh@gmail.com>"]
edition = "2021"
rust-version = "1.71"
homepage = "https://beta.ruff.rs/docs"
documentation = "https://beta.ruff.rs/docs"
repository = "https://github.com/astral-sh/ruff"
license = "MIT"
resolver = "2"

[lib]

[dependencies]
ruff = { path = "../ruff" }
ruff_cache = { path = "../ruff_cache" }
ruff_macros = { path = "../ruff_macros" }
dirs = { version = "5.0.0" }
pep440_rs = { version = "0.3.1", features = ["serde"] }
anyhow = { version = "1.0.69" }
colored = { version = "2.0.0" }
ignore = { version = "0.4.20" }
itertools = { version = "0.10.5" }
log = { version = "0.4.17" }
glob = { version = "0.3.1" }
globset = { version = "0.4.10" }
path-absolutize = { version = "3.1.1" }
regex = { version = "1.9.5" }
rustc-hash = { version = "1.1.0" }
schemars = { version = "0.8.12" , optional = true }
serde = { version = "1.0.152", features = ["derive"] }
shellexpand = { version = "3.0.0" }
strum = { version = "0.25.0", features = ["strum_macros"] }
toml = { version = "0.7.8" }


[features]
schemars = [ "dep:schemars" ]
