[tool.poetry]
name = "noteblock-generator"
version = "0.1.6.2"
description = "Generate music compositions in Minecraft noteblocks."
authors = ["Felix Fourcolor <felix.fourcolor@gmail.com>"]
readme = "README.md"
packages = [{include = "noteblock_generator"}]
repository = "https://github.com/FelixFourcolor/noteblock-generator"
keywords = ["minecraft", "note block", "music"]

[tool.poetry.scripts]
noteblock-generator = "noteblock_generator.main:main"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
amulet-core = "^1.9.18"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.325"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
strictParameterNoneValue = false
