[tool.poetry]
name = "lonedruid"
version = "0.6.2"
description = ""
authors = ["lone_druid <enikita332@gmail.com>"]
readme = "README.md"
repository = "https://github.com/NikitaNightBot/LoneDruid"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
