[tool.poetry]
name = "stecker"
version = "1.0.0b0"
description = "Plugin framework using subclasses and entrypoints"
authors = ["Jonathan Weth <dev@jonathanweth.de>", "Dominik George <nik@naturalnet.de>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://edugit.org/AlekSIS/libs/stecker"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
