[tool.poetry]
name = "nlp-data"
version = "0.1.1"
description = ""
authors = ["wang mengdi <wangmengdi@pachiratech.com>"]
readme = "README.md"
packages = [{include = "nlp_data"}]

[tool.poetry.dependencies]
python = "^3.7"
datasets = ">=2.14.1"
docarray = {"extras" = ["aws"], version = ">=0.37.1"}
boto3 = ">=1.28.8"
openpyxl = ">=3.1.2"
pandas = ">=2.1.0"
wasabi = ">=1.1.1"
tqdm = ">=4.65.0"
rich = ">=13.4.2"
pydantic = ">=1.10.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
