# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - refs/tags/v*
variables:
  - group: "PyPI Variables"

pool:
  vmImage: ubuntu-latest

steps:
  - script: python -m venv venv
    displayName: setup venv
  - script: source venv/bin/activate
    displayName: activate venv
  - script: pip install -r requirements.txt
    displayName: install requirements
  - script: rm -fr dist
    displayName: build repo
  - script: python -m build
    displayName: build dependency
  - script: python -m twine upload dist/* -u __token__ -p $(PYPI_TOKEN)
    displayName: publish to pypi
