[tool.poetry]
name = "mycoolpackage-bdd4329"
version = "0.1.6"
description = "A useful description"
authors = ["Shannon Byrnes <sbyrnes@internet2.edu>"]
readme = "README.md"
packages = [{include = "my_cool_package"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
