[tool.poetry]
name = "examon_beginners_package"
version = "0.3.0"
description = ""
authors = ["Jarrod Folino <jdfolino@icloud.com>"]
packages = [{include = "examon_beginners_package"}]


[tool.poetry.dependencies]
python = ">3.9,<3.12"
examon-core = "1.4.0"
simple-term-menu = "^1.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
